# Generated by Django 5.0.6 on 2026-09-29 08:49

import django.core.validators
import invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('message', models.TextField(max_length=500)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guestbook message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=200, verbose_name='Question (English)')),
                ('question_ar', models.CharField(max_length=200, verbose_name='Question (Arabic)')),
                ('answer', models.CharField(choices=[('groom', 'The groom'), ('bride', 'The bride')], max_length=5)),
                ('reveal_en', models.CharField(blank=True, max_length=200, verbose_name='Fun fact after answering (English)')),
                ('reveal_ar', models.CharField(blank=True, max_length=200, verbose_name='Fun fact after answering (Arabic)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quiz question',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('attending', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('title_en', models.CharField(max_length=80, verbose_name='Title (English)')),
                ('title_ar', models.CharField(max_length=80, verbose_name='Title (Arabic)')),
                ('icon', models.CharField(default='✨', help_text='An emoji, e.g. 💍 🍽️ 💃', max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Schedule item',
                'ordering': ['order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ScratchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=160, verbose_name='Message (English)')),
                ('text_ar', models.CharField(max_length=160, verbose_name='Message (Arabic)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Scratch-card message',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name_en', models.CharField(default='Abdelfattah', max_length=60, verbose_name='Groom name (English)')),
                ('groom_name_ar', models.CharField(default='عبدالفتاح', max_length=60, verbose_name='Groom name (Arabic)')),
                ('bride_name_en', models.CharField(default='Hoda', max_length=60, verbose_name='Bride name (English)')),
                ('bride_name_ar', models.CharField(default='هدى', max_length=60, verbose_name='Bride name (Arabic)')),
                ('couple_photo', models.ImageField(blank=True, help_text='Optional. Shown in the couple section. Portrait photos look best.', upload_to='couple/')),
                ('couple_message_en', models.TextField(blank=True, default="Two hearts, one story — and we'd love for you to be part of its most beautiful chapter.", verbose_name='Couple message (English)')),
                ('couple_message_ar', models.TextField(blank=True, default='قلبين وحكاية واحدة… ويسعدنا تكونوا معانا في أحلى فصل فيها.', verbose_name='Couple message (Arabic)')),
                ('wedding_datetime', models.DateTimeField(default=invitation.models.default_wedding_datetime, help_text='Used by the countdown. Time zone: Africa/Cairo.')),
                ('venue_name_en', models.CharField(default='Acacia Hall', max_length=100, verbose_name='Venue name (English)')),
                ('venue_name_ar', models.CharField(default='قاعة أكاسيا', max_length=100, verbose_name='Venue name (Arabic)')),
                ('venue_address_en', models.CharField(default='El Bagour, Menoufia, Egypt', max_length=200, verbose_name='Venue address (English)')),
                ('venue_address_ar', models.CharField(default='الباجور، المنوفية', max_length=200, verbose_name='Venue address (Arabic)')),
                ('google_maps_url', models.URLField(default='https://www.google.com/maps/search/?api=1&query=Acacia+Hall+El+Bagour+Menoufia+Egypt', help_text='Paste the share link of the venue from Google Maps.', max_length=500)),
                ('location_qr_code', models.ImageField(blank=True, help_text='Upload the venue QR code image. It is displayed at full sharpness, never stretched.', upload_to='qr/', verbose_name='Location QR code')),
                ('song', models.FileField(blank=True, help_text='The wedding song (mp3 recommended). The music button is hidden until a song is uploaded.', upload_to='music/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'aac', 'ogg', 'wav'])])),
                ('song_title', models.CharField(blank=True, help_text='Optional, e.g. the song name.', max_length=120)),
                ('share_image', models.ImageField(blank=True, help_text='Optional preview image when the link is shared on WhatsApp / Facebook (1200×630).', upload_to='share/')),
                ('guestbook_auto_approve', models.BooleanField(default=True, help_text='If off, new guestbook messages stay hidden until you approve them.')),
                ('guestbook_open', models.BooleanField(default=True, help_text='Allow new guestbook messages.')),
                ('rsvp_open', models.BooleanField(default=True, help_text='Allow new RSVP responses.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitation settings',
                'verbose_name_plural': 'Invitation settings',
            },
        ),
    ]
